### ISSUE TITLE
Confusing cpu cgroup desc.

### ISSUE THREAD

**Issue by andrewchambers** [google/nsjail#101]
```
--cgroup_cpu_ms_per_sec VALUE
	Number of us that the process group can use per second (default: '0' - disabled)
```

ms_per_sec implies milliseconds, but the description says 'us', is that a contradictory micro seconds?

**Comment by robertswiecki** [comment]
Thanks, fixed in 432c38ad238dd64a5d66e73e0e01fbe5c310c0fd
