### ISSUE TITLE
Build sandboxing disabled due to nsjail error. This may become fatal in the future.

### ISSUE THREAD

**Issue by DiamondMiner88** [google/nsjail#110]
I was following a tutorial on how to build android.
These were the following steps:
`make clobber`
`source build/envsetup.sh`
`lunch aosp_marlin_userdebug`
`setpaths`
`make -j4`
When I execute the `lunch` and `setpaths` I get this spammed in the console:
`18:50:02 Build sandboxing disabled due to nsjail error. This may become fatal in the future.`
`18:50:02 Please let us know why nsjail doesn't work in your environment at:`
`18:50:02   https://groups.google.com/forum/#!forum/android-building`
`18:50:02   https://issuetracker.google.com/issues/new?component=381517`
Also after i execute `lunch` after i get the above error i get this:
`============================================`
`PLATFORM_VERSION_CODENAME=Q`
`PLATFORM_VERSION=Q`
`TARGET_PRODUCT=aosp_marlin`
`TARGET_BUILD_VARIANT=userdebug`
`TARGET_BUILD_TYPE=release`
`TARGET_ARCH=arm64`
`TARGET_ARCH_VARIANT=armv8-a`
`TARGET_CPU_VARIANT=kryo`
`TARGET_2ND_ARCH=arm`
`TARGET_2ND_ARCH_VARIANT=armv8-a`
`TARGET_2ND_CPU_VARIANT=kryo`
`HOST_ARCH=x86_64`
`HOST_2ND_ARCH=x86`
`HOST_OS=linux`
`HOST_OS_EXTRA=Linux-4.4.0-17763-Microsoft-x86_64-Ubuntu-18.04.2-LTS`
`HOST_CROSS_OS=windows`
`HOST_CROSS_ARCH=x86`
`HOST_CROSS_2ND_ARCH=x86_64`
`HOST_BUILD_TYPE=release`
`BUILD_ID=PI`
`OUT_DIR=out`
`============================================`
My environment is WSL Ubuntu

**Comment by happyCoder92** [comment]
The issue seems to be related to the nsjail setup in Android build system and not nsjail itself.
The proper place to report the problem is in the error message:
https://issuetracker.google.com/issues/new?component=381517
It seems however that there is already a similar report:
https://issuetracker.google.com/issues/123210688
That said we did not really test nsjail on Windows Subsystem for Linux.

**Comment by rares1337** [comment]
dasd

**Comment by Mic-360** [comment]
> I was following a tutorial on how to build android.
> These were the following steps:
> `make clobber`
> `source build/envsetup.sh`
> `lunch aosp_marlin_userdebug`
> `setpaths`
> `make -j4`
> When I execute the `lunch` and `setpaths` I get this spammed in the console:
> `18:50:02 Build sandboxing disabled due to nsjail error. This may become fatal in the future.`
> `18:50:02 Please let us know why nsjail doesn't work in your environment at:`
> `18:50:02 https://groups.google.com/forum/#!forum/android-building`
> `18:50:02 https://issuetracker.google.com/issues/new?component=381517`
> Also after i execute `lunch` after i get the above error i get this:
> `============================================`
> `PLATFORM_VERSION_CODENAME=Q`
> `PLATFORM_VERSION=Q`
> `TARGET_PRODUCT=aosp_marlin`
> `TARGET_BUILD_VARIANT=userdebug`
> `TARGET_BUILD_TYPE=release`
> `TARGET_ARCH=arm64`
> `TARGET_ARCH_VARIANT=armv8-a`
> `TARGET_CPU_VARIANT=kryo`
> `TARGET_2ND_ARCH=arm`
> `TARGET_2ND_ARCH_VARIANT=armv8-a`
> `TARGET_2ND_CPU_VARIANT=kryo`
> `HOST_ARCH=x86_64`
> `HOST_2ND_ARCH=x86`
> `HOST_OS=linux`
> `HOST_OS_EXTRA=Linux-4.4.0-17763-Microsoft-x86_64-Ubuntu-18.04.2-LTS`
> `HOST_CROSS_OS=windows`
> `HOST_CROSS_ARCH=x86`
> `HOST_CROSS_2ND_ARCH=x86_64`
> `HOST_BUILD_TYPE=release`
> `BUILD_ID=PI`
> `OUT_DIR=out`
> `============================================`
> My environment is WSL Ubuntu

Did You found Fix of this nsjail error ? if yes, then please tell me

**Comment by DiamondMiner88** [comment]
Nope I didn't, and no longer care. Just use a Linux VM

**Comment by Sean-K-Wu** [comment]
> 

I met too , did u solve?

**Comment by Sean-K-Wu** [comment]
> I met this error when I use centos 7 to build the Android source code , Did anyone solved this problem ?

I met too , did u solve?

**Comment by Kfkcome** [comment]
> > I met this error when I use centos 7 to build the Android source code , Did anyone solved this problem ?
> 
> I met too , did u solve?

I met too in centos 7 ,did you solve it?

**Comment by flyfishxu** [comment]
I met in Ubuntu 24.04(not WSL or Docker), it seems like a problem of Google, maybe.

**Comment by Bush-cat** [comment]
> I met in Ubuntu 24.04(not WSL or Docker), it seems like a problem of Google, maybe.
might be this issue/feature of 24.04
https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2063976

you can try this
https://discourse.ubuntu.com/t/noble-numbat-release-notes/39890#unprivileged-user-namespace-restrictions-15

**Comment by vehoelite** [comment]
I was able to clear the error by not using sudo. You may need to sudo chown user:user -R /android/source if you get any permission errors.
