### ISSUE TITLE
Misleading command in sample config

### ISSUE THREAD

**Issue by lwshuo** [google/nsjail#113]
in imagemagick-convert.cfg , it already has exec_bin  with the convert command. But the example command inside description also has the command. That will get treated as parameter for convert and cause a no decode delegate for image format error. Can somebody fix it?

**Comment by robertswiecki** [comment]
I think this is a more stable solution for the future - i.e. allowing to override config with cmdline

https://github.com/google/nsjail/commit/2b1bad6b5bf17935af57f0e18701d00b7019ad34
