### ISSUE TITLE
No tty for interactive bash

### ISSUE THREAD

**Issue by ariutta** [google/nsjail#117]
The  [example "Bash in a minimal file-system"](https://github.com/google/nsjail/blob/4628ded4796607211655a37f1e357a0ce917fe3c/README.md#bash-in-a-minimal-file-system-with-uid0-and-access-to-devurandom-only) from the README gives the following message:

>bash: cannot set terminal process group (-1): Inappropriate ioctl for device
>bash: no job control in this shell

Is that expected behavior or an error?

*More Details*

This message is displayed because the example invokes an interactive shell (`/bin/bash -i`) but doesn't give it a tty. Using the option `--skip_setsid` avoids that message.

**Comment by robertswiecki** [comment]
It's expected, owning the tty (not using setsid) would mean that a spawned process can put some characters into tty's backbuffer with ioctl, so by default spawaned processes don't own the terminal

**Comment by robertswiecki** [comment]
Please reopen if you'd like to follow-up on that.
