### ISSUE TITLE
--cwd doesn't work with --disable_clone_newns

### ISSUE THREAD

**Issue by rprichard** [google/nsjail#121]
It looks like `--cwd` is ignored when `--disable_clone_newns` is also specified. Is this intended?

e.g. Without `--disable_clone_newns`, `--cwd` works as expected:

```
rprichard@cashew:/x/nsjail$ ./nsjail --chroot / --cwd /usr/local/bin -q /bin/pwd
/usr/local/bin
```

With `--disable_clone_newns`, `--cwd` is apparently ignored:

```
rprichard@cashew:/x/nsjail$ ./nsjail --disable_clone_newns --cwd /usr/local/bin -q  /bin/pwd
/x/nsjail
rprichard@cashew:/x/nsjail$ ./nsjail --disable_clone_newns --chroot / --cwd /usr/local/bin -q  /bin/pwd
/
```

FWIW, I'm interested in `--disable_clone_newns` because it reduces the overhead of running nsjail from ~110ms to ~40ms.

**Comment by robertswiecki** [comment]
Thx for the report, should be fixed with https://github.com/google/nsjail/commit/c291b11ae6b63304b73d6badec68f8ecf5f14d3f

**Comment by rprichard** [comment]
The second case is fixed, but not the first one (which exits early when no chroot is specified).

```
rprichard@cashew:/x/nsjail$ ./nsjail --disable_clone_newns --cwd /usr/local/bin -q  /bin/pwd
/x/nsjail
rprichard@cashew:/x/nsjail$ ./nsjail --disable_clone_newns --chroot / --cwd /usr/local/bin -q  /bin/pwd
/usr/local/bin
```

**Comment by robertswiecki** [comment]
Thanks, possibly fixed with https://github.com/google/nsjail/commit/d9efc0b3a7d74a89e632cb6a21a5ad275fe1b3dc
