### ISSUE TITLE
config.proto: envar

### ISSUE THREAD

**Issue by ukai** [google/nsjail#122]
in config.proto, comment says envvar,
```
    /* EnvVars to be set before executing binaries. If the envvar doesn't contain '='
       (e.g. just the 'DISPLAY' string), the current envvar value will be used */
```

but actual field is envar.
```
    repeated string envar = 20;
```

**Comment by ukai** [comment]
oops, missed 
config.cc:              cmdline::addEnv(nsjconf, njc.envar(i));

**Comment by robertswiecki** [comment]
Thanks @ukai I standardized on envar with https://github.com/google/nsjail/commit/e2c5c59bd32beac7203a0d46a42df77c934ac1f2
