### ISSUE TITLE
A typo in the dockerfile

### ISSUE THREAD

**Issue by wangluochao902** [google/nsjail#141]
https://github.com/google/nsjail/blob/a378ca0e96be54dba0dc6e58246311b282138649/Dockerfile#L20
Hi, we are developing a tool to detect typos/bugs in dockerfiles automatically. Our tool finds a potential typo above. The rm command has a long option prefix "--" without specifying an long option. Or the "--" is used to remove a file whose name starts with "-".  Our tool is currently available here https://wangluochao902.github.io/clcheck/

**Comment by fluxchief** [comment]
Hi, `--` is used to tell the option parser that no more options will follow. it is not needed in this case but does not hurt.
