### ISSUE TITLE
Cgroup mem max: bytes or MiB?

### ISSUE THREAD

**Issue by MihanixA** [google/nsjail#146]
Documentations says `--cgroup_mem_max` is in bytes:
https://github.com/google/nsjail/blame/0fbbb9566635e3f6c33697d2b34c950709d609ac/README.md#L250

Found this in `config.proto` saying its in MiB
https://github.com/google/nsjail/blob/f7554882fe44db576e688b9b21e4f46f5229da30/config.proto#L199

Than I decided to test this in my nsjail container:
```
root@d4a84b28ab73:/# echo "
> int main () {
>     long x[10000000000];
> }
> " > ml.cpp
root@d4a84b28ab73:/# g++ ml.cpp -o ml_exec
root@d4a84b28ab73:/# time nsjail -Mo --user 99999 --group 99999 --chroot / --time_limit 1 --cgroup_mem_max 1000000 --max_cpus 1 --cgroup_pids_max 1 --exec_file ml_exec
```
And as a surprise, I got
`[I][2020-07-16T04:10:50+0000] pid=61 ([STANDALONE MODE]) exited with status: 0, (PIDs left: 0)`
But,
```
root@d4a84b28ab73:/# time nsjail -Mo --user 99999 --group 99999 --chroot / --time_limit 1 --cgroup_mem_max 1024 --max_cpus 1 --cgroup_pids_max 1 --exec_file ml_exec
```
Got expected 
`[I][2020-07-16T04:10:30+0000] pid=59 ([STANDALONE MODE]) terminated with signal: SIGKILL (9), (PIDs left: 0)`

Am I doing something wrong or is it actually in MiB, not bytes?

**Comment by disconnect3d** [comment]
Note that `long x[10000000000];` is a stack allocation of `10_000_000_000` which is ~10 GB.

The stack is also limited by the `rlimit_stack` value which was fixed/changed to 8MB by default in nsjail config recently: https://github.com/google/nsjail/pull/129.

**Comment by disconnect3d** [comment]
Regarding the `cgroup_mem_max`, tl;dr: we do not multiply it by 1024*1024 (as we do with e.g., `rlimit_stack`) and the files we write to support many units, but if a unit is not specified, bytes are used, so indeed `in MiB` is wrong.

Some investigation logs below ;).

### For cgroups v1
https://github.com/google/nsjail/blob/0b1d5ac03932c140f08536ed72b4b58741e7d3cf/cgroup.cc#L67-L78

We write to the `memory.limit_in_bytes` file of cgroups memory controller.  From the [documentation](https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt) it seems that if you write a number there, it will be in bytes, but you can also use suffixes to specify the unit:
> 7.1 Interface
> 
> Soft limits can be setup by using the following commands (in this example we
> assume a soft limit of 256 MiB)
> 
> \# echo 256M > memory.soft_limit_in_bytes
> 
> If we want to change this to 1G, we can at any time use
> 
> \# echo 1G > memory.soft_limit_in_bytes
> 
> NOTE1: Soft limits take effect over a long period of time, since they involve
>        reclaiming memory for balancing between memory cgroups
> NOTE2: It is recommended to set the soft limit always below the hard limit,
>        otherwise the hard limit will take precedence.

## For cgroups v2
https://github.com/google/nsjail/blob/0b1d5ac03932c140f08536ed72b4b58741e7d3cf/cgroup2.cc#L86-L95

We write to the `memory.max` file. From the [documentation](https://www.kernel.org/doc/Documentation/cgroup-v2.txt):
> Memory Interface Files
> ~~~~~~~~~~~~~~~~~~~~~~
> 
> All memory amounts are in bytes.  If a value which is not aligned to
> PAGE_SIZE is written, the value may be rounded up to the closest
> PAGE_SIZE multiple when read back.
> 
> (...)
> 
>   memory.max
> 	A read-write single value file which exists on non-root
> 	cgroups.  The default is "max".
> 
> 	Memory usage hard limit.  This is the final protection
> 	mechanism.  If a cgroup's memory usage reaches this limit and
> 	can't be reduced, the OOM killer is invoked in the cgroup.
> 	Under certain circumstances, the usage may go over the limit
> 	temporarily.
> 
> 	This is the ultimate protection mechanism.  As long as the
> 	high limit is used and monitored properly, this limit's
> 	utility is limited to providing the final safety net.

**Comment by disconnect3d** [comment]
A bit out of topic, but I think it would be good to elaborate a bit more on your example.

> Note that `long x[10000000000];` is a stack allocation of `10_000_000_000` which is ~10 GB.
> 
> The stack is also limited by the `rlimit_stack` value which was fixed/changed to 8MB by default in nsjail config recently: #129.

Such stack allocation **does not ask system for more memory** and it only does change the stack pointer "so that the stack frame will be able to hold this big array". This makes the stack pointer get an invalid value (outside of program stack memory). However, since the program does not access this memory, it does not crash.

**Disclaimer: all above depends on your ulimits, so if you set a huge stack size via ulimits/rlimits, you will be able to hold such big array.**

Anyway, we can observe, that the program you send will crash (on default/usual setups) by modifying it a bit:
```c
int main () {
#define SIZE 10000000000
    long x[SIZE];
    x[0] = 0;
}
```
And its execution (I used [pwndbg](https://github.com/pwndbg/pwndbg) GDB plugin):
![image](https://user-images.githubusercontent.com/10009354/87673275-91888b00-c774-11ea-93d1-8a1c73b1a08b.png)

**Comment by MihanixA** [comment]
I ran through the same docs, but `config.proto` made me confused. Now I see, thank you.

I am a Python user and I don't have such deep understanding of C++ %) 
Though, again thank you very much for this detailed answer, that was interesting to know!
