### ISSUE TITLE
Running nsjail on TCP mode in a docker container behaves weirdly

### ISSUE THREAD

**Issue by aryan9600** [google/nsjail#151]
Trying to create a simple chroot enviornment and `nc` into it. 
Running `nsjail -Ml --port 9000 --chroot ~/practice-jail --user 99999 --group 99999 -- /bin/bash` works perfectly. But running the same command using docker doesn't behave as expected.
Command: `docker run -p 9000:9000 --privileged -it nsjailcontainer nsjail -Ml --disable_proc  --port 9000 --chroot ~/practice-jail --user 99999 --group 99999 -- /bin/bash`
When I run `nc 127.0.0.1 9000`, I get the following error:
```
void cmdline::logParams(nsjconf_t*)():264 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[I][2020-08-26T14:08:04+0000] Listening on [::]:9000
[I][2020-08-26T14:08:07+0000] New connection from: [::ffff:172.17.0.1]:50638 on: [::ffff:172.17.0.2]:9000
bool mnt::mountPt(mount_t*, const char*, const char*)():203 mount(''/home/ubuntu/practice-jail' -> '/' flags:MS_RDONLY|MS_BIND|MS_REC|MS_PRIVATE type:'' options:'' dir:true') src:'/home/ubuntu/practice-jail' dstpath:'/tmp/nsjail.0.root//' failed: No such file or directory
[F][2020-08-26T14:08:07+0000][1] bool subproc::runChild(nsjconf_t*, int, int, int, int)():448 Launching child process failed
[W][2020-08-26T14:08:07+0000][1] bool subproc::runChild(nsjconf_t*, int, int, int, int)():478 Received error message from the child process before it has been executed
[I][2020-08-26T14:08:07+0000] pid=6 ([::ffff:172.17.0.1]:50638) exited with status: 255, (PIDs left: 0)
```

Any idea what I might be doing wrong?

**Comment by pomo-mondreganto** [comment]
You're using the `~/practice-jail` path in your chroot directive. In the second case, the command is executed in Docker under another user, so the directory is missing.

**Comment by aryan9600** [comment]
Thanks!
