### ISSUE TITLE
Feature request: kill on disconnect (--mode l)

### ISSUE THREAD

**Issue by NieDzejkob** [google/nsjail#152]
Currently, when the client disconnects, nsjail will close the I/O pipes, but let the child process live. I would've expected the process to get killed, and I believe an option to enable such behavior would be useful.

**Comment by robertswiecki** [comment]
Thanks for the report - this should do it - https://github.com/google/nsjail/commit/608618ea7b807fdb18eebdea9e15436df3bdc98f
