### ISSUE TITLE
Log is partly written to stderr when --log option is passed

### ISSUE THREAD

**Issue by pomo-mondreganto** [google/nsjail#153]
When running nsjail with both config file and command-line parameters, like this: 

```
nsjail --config config.cfg --log log.txt --chroot / --exec_file /bin/ls / 1>stdout 2>stderr
```

I get the following `stderr` file contents:

```
[D][2020-09-02T15:15:06+0100][611] bool config::parseFile(nsjconf_t*, const char*)():320 Parsed config:
'name: "some name"
log_level: DEBUG
'
```

My `config.cfg` file is:

```
name: "some name"
log_level: DEBUG
```

So, the first line of nsjail log is being written to stderr, effectively leaking the configuration. 

The rest of the log gets stored at `log.txt`, as expected.

I'm running nsjail from the Docker image at https://hub.docker.com/r/disconnect3d/nsjail/, so it might be fixed already. In that case, I'd like to ask @disconnect3d to update the image, as this bug is quite annoying in my setup. Thanks!

**Comment by fluxchief** [comment]
Hi,

What exactly is the issue here? It is using debug logging in https://github.com/google/nsjail/blob/master/config.cc#L317 so if you reduce the log level you won't see this message, in my current understanding this is working as intended.

**Comment by pomo-mondreganto** [comment]
I think when `--log` option is passed from the command line, it should take precedence and switch the logging to that file. It's strange the log gets split into two with one line hanging in stderr and everything else written to log file.

**Comment by fluxchief** [comment]
In that case shouldn't you use that setting in the config file?
https://github.com/google/nsjail/blob/master/config.proto#L106

> it should take precedence and switch the logging to that file
Unless documented otherwise I don't think that that's a bug. It is an implementation detail and only depending on in which order things are getting parsed.
And there are ways of configuring it properly by just not mixing both options to provide the configuration.
Did you try setting the loglevel only as command line parameter (using --verbose) instead of setting it in the config? I'm haven't checked but I think that might already solve your issue.

**Comment by pomo-mondreganto** [comment]
Thanks, I'll try that.

The reason behind it all is that passing dynamic options to command line is easier than generating the config with some templating (if some options are "static" and don't change between runs and others -- like log file -- are dynamic & generated for each invocation).

**Comment by fluxchief** [comment]
Looking at the code it might also work if you provide `--log` before `--config` (assuming getopt keeps the order of arguments).

**Comment by pomo-mondreganto** [comment]
Tried the last suggestion (passing `--log` before `--config`) and it seems to work, which solves my problem good enough. Thank you!
