### ISSUE TITLE
mnt initCloneNs bug crash

### ISSUE THREAD

**Issue by micron10** [google/nsjail#155]
Hi i try to run nsjail but have problem : 

run with this commad 
./nsjail --disable_proc --macvlan_iface eth0  --macvlan_vs_ip 192.168.10.2 --macvlan_vs_nm 255.255.255.0 --macvlan_vs_gw 192.168.10.1 -Ml --disable_no_new_privs -- /bin/sh -i

and try to connect with : nc 127.0.0.1 37653

[I][2020-09-11T10:10:55+0300] Mode: LISTEN_TCP
[I][2020-09-11T10:10:55+0300] Jail parameters: hostname:'NSJAIL', chroot:'', process:'/bin/sh', bind:[::]:0, max_conns_per_ip:0, time_limit:0, personality:0, daemonize:false, clone_newnet:true, clone_newuser:true, clone_newns:true, clone_newpid:true, clone_newipc:true, clone_newuts:true, clone_newcgroup:true, keep_caps:false, disable_no_new_privs:true, max_cpus:0
[I][2020-09-11T10:10:55+0300] Mount: '/' flags:MS_RDONLY type:'tmpfs' options:'' dir:true
[I][2020-09-11T10:10:55+0300] Uid map: inside_uid:0 outside_uid:0 count:1 newuidmap:false
[W][2020-09-11T10:10:55+0300][6378] void cmdline::logParams(nsjconf_t*)():252 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[I][2020-09-11T10:10:55+0300] Gid map: inside_gid:0 outside_gid:0 count:1 newgidmap:false
[W][2020-09-11T10:10:55+0300][6378] void cmdline::logParams(nsjconf_t*)():262 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[I][2020-09-11T10:10:55+0300] Listening on [::]:37653
[I][2020-09-11T10:11:02+0300] New connection from: [::ffff:127.0.0.1]:41104 on: [::ffff:127.0.0.1]:37653
[E][2020-09-11T10:11:02+0300][1] bool mnt::initCloneNs(nsjconf_t*)():411 pivot_root('/tmp/nsjail.0.root', '/tmp/nsjail.0.root'): Invalid argument
[F][2020-09-11T10:11:02+0300][1] bool subproc::runChild(nsjconf_t*, int, int, int, int)():448 Launching child process failed
[W][2020-09-11T10:11:02+0300][6378] bool subproc::runChild(nsjconf_t*, int, int, int, int)():478 Received error message from the child process before it has been executed
[I][2020-09-11T10:11:02+0300] pid=6413 ([::ffff:127.0.0.1]:41104) exited with status: 255, (PIDs left: 0)

**Comment by robertswiecki** [comment]
Ho, you need to specify some root directory, try

```shell
--chroot /
```

**Comment by happyCoder92** [comment]
Are you chrooted?
Are you running inside docker?

**Comment by robertswiecki** [comment]
Closing due to ENOINFO
