### ISSUE TITLE
Documentation: example for microservice setup

### ISSUE THREAD

**Issue by Zyl9393** [google/nsjail#156]
How would I arrange a typical small-scale microservice scenario (e.g. Internet user <-> HTTP server <-> Database process) with nsjail? Is there even an option to lift some of the restrictions of the jailed process so that it can establish connections itself to
1. the internet (e.g. external API)
2. another process on the same host (e.g. database)
?

I am asking because this project looks like a sleek way to get isolation without adopting a solution such as Docker with all of its deadweight. (their shipment metaphors really check out don't they?)

**Comment by happyCoder92** [comment]
You can use:
```
--disable_clone_newnet|-N 
```
This will however weaken the isolation as the process will run with the host network namespace.

**Comment by emsd1981** [comment]
Ok
