### ISSUE TITLE
seccomp violation log: always show SiSyscall: 31 ?

### ISSUE THREAD

**Issue by ukai** [google/nsjail#158]
when nsjail detected seccomp violation, it logs

```
[W][2021-01-29T07:58:12+0000][7742] void subproc::seccompViolation(nsjconf_t*, siginfo_t*)():258 pid=7743 committed a syscall/seccomp violation and exited with SIGSYS
[W][2021-01-29T07:58:12+0000][7742] void subproc::seccompViolation(nsjconf_t*, siginfo_t*)():288 pid=7743, SiSyscall: 31, SiCode: 2, SiErrno: 0, SiSigno: 17, SP: 0, PC: 0
```

Initially I thought it was caused by syscall=31 ("shmctl"?), but actual violation seems to be syscall=12 ("brk", because I didn't have "brk" in ALLOW and DEFAULT KILL) ? 

according to journalctl
```
Jan 29 07:58:12 [reducted] audispd[568]: node=[reducted] type=SECCOMP msg=audit(1611907092.540:26626): auid=22776 uid=22776 gid=89939 ses=11 subj==untrusted (complain) pid=7743 comm="clang++" exe="/usr/local/google/home/ukai/tmp/try-sample2/root/third_party/llvm-build/Release+Asserts/bin/clang" sig=31 arch=c000003e syscall=12 compat=0 ip=0x7fa45496bcb7 code=0x0
```

**Comment by robertswiecki** [comment]
This is just the signal number 31==SIGSYS. The Linux kernel used to report the actual syscall here, but it suffered from some race conditions, and it was replaced by the signal instead. The only way of fetching this data is through 'dmesg', and there's no regular kernel API to do this to my knowledge.

**Comment by ukai** [comment]
ah, I see.  so `siginfo_t` is meaningless for `SECCOMP_RET_KILL_PROCESS`?

then, it is just confusing that it logs in `seccompViolation()` ? better to log that says "check dmesg for violation detail" or something instead?

**Comment by ukai** [comment]
btw, I can't find the info via `dmesg`, but via `journalctl` (`audispd`?)

**Comment by robertswiecki** [comment]
Good idea. Added in https://github.com/google/nsjail/commit/e1e80e8efa902f4c01c4bb39aa72af99c97b8a37
