### ISSUE TITLE
nsjail in German context

### ISSUE THREAD

**Issue by juliangruber** [google/nsjail#161]
Hey! As a German, nsjail is kind of an unfortunate name, as `ns` stands for nationalist socialist and that (in context of German history) together with jail is an unfortunate combination. I guess here `ns` stands for namespace.

Not sure if it's really offensive, just uncomfortable to me personally. I just wanted to make you aware of this.

Keep up the great work!

**Comment by cblichmann** [comment]
Hi there, fellow German here!

While I was not personally involved in the naming, using the `ns` prefix to denote "namespace" is common industry practice and seems to acceptable at least among native English speakers (and I'm not aware that is is widely associated with a political connotation in tech circles).

In computing "NS" and "ns" are also commonly used for (among others):
- Name servers in the Domain Name System
- Neighbor Solicitation, as part of IPv6
- NeXTSTEP, the OS that had a huge influence on macOS -- nearly all system-provided classes and APIs to this day start with that prefix

I can definitely relate with the feeling of being uncomfortable about this, though I'm not exactly sure where to go from here. nsjail is a project with collaborators from many different countries and place great respect and trust in each other.

If you feel strongly about it, Google also provides other sandboxing tools and technologies, such as:
- minijail - https://android.googlesource.com/platform/external/minijail/
- Sandboxed API and Sandbox2 - https://developers.google.com/sandboxed-api

**Comment by juliangruber** [comment]
Thank you for your detailed answer! And I didn't assume any disrespect at all, I more wanted to check my own assumptions, see whether this would be an issue or I just should move on. Reading your answer, I also remembered more and more tools using the `ns` prefix. I'm absolutely fine keeping this name, I'll close this then.
