### ISSUE TITLE
Is commnent line allowed in .cfg file?

### ISSUE THREAD

**Issue by edwardt** [google/nsjail#167]
None of the .cfg files in the configs directories shows comment other than descriptions.
What if I want to document what a set of mount points is about? IS there a way to do something like 
For example for configs/apache.cfg:
 ```
# my comment here
mount {
	src: "/etc/apache2"
	dst: "/etc/apache2"
	is_bind: true
}
```
If so, where is the documentation for this, if not the location of the source code?
Only found reference to src code here:
https://github.com/google/nsjail/blob/master/config.cc#L308
google::protobuf::TextFormat::Parser()
but does not seem t have documentation if # is supported or not explicitly
in the serialized text format

There's reference to comment style in protobuf, but which style is applicable to .cfg file?
https://github.com/protocolbuffers/protobuf/blob/bc45f92262a8e0e6e1ab7302c72a380eb0346f8e/src/google/protobuf/io/tokenizer.h#L232

Here?
https://github.com/protocolbuffers/protobuf/blob/6051341ab21b4e1f75e91710ab1a8cc8fadda521/src/google/protobuf/text_format.cc#L272

**Comment by robertswiecki** [comment]
Hi,

I'm unsure - we indeed depend on the libprotobuf, so whatever its text proto parser supports, we support as well. 

Would you like us to enable treating ```#``` as a comment explicitly? I guess we can do that, given that it's the default behavior of the library anyway.

**Comment by edwardt** [comment]
@robertswiecki 
Yes please do. 
There are 2 comment style as in here:
https://github.com/protocolbuffers/protobuf/blob/bc45f92262a8e0e6e1ab7302c72a380eb0346f8e/src/google/protobuf/io/tokenizer.h#L232
C-style comment is documented by protobuf for .proto files # is not.

**Comment by robertswiecki** [comment]
I don't think it's possible from the TextFormat high-level API, the call you mentioned is hidden in the ParserImpl constructor, and b/c the parsing procedure is something like

```C
ParserImpl impl(..../params/...);
return impl.Parse(input);
```

there's no way to change values of ParserImpl::tokenizer_ bafore ::Parse() is called.

We could maybe provide our own parsing procedure, but it uses details of the TextFormat::Parser to instantiate ParserImpl, and we'll have to make sure it compiles every time ParserImpl or TextFormat::Parser gets changed. 

I suggest just using ```#```, it seems to be de-facto standard. The ```//``` you mentioned is used in .proto files, and not in textformat representation of protos.

**Comment by edwardt** [comment]
@robertswiecki 
Can you document this in for nsjail? I think most people will be just fine if it is documented. There is little point to change or mimic the protobuf parser.

**Comment by robertswiecki** [comment]
I added some comments to sample configs with https://github.com/google/nsjail/commit/3ac7856b673604b9a655de138d4b2a924450cbba - this will work as a safeguard - making us know if something changes wrt parsing proto messages
