### ISSUE TITLE
nsjail + java/tomcat

### ISSUE THREAD

**Issue by farconada** [google/nsjail#17]
_context: trying nsjail under CentOS 7 with java/tomcat package from yum repos_

How can I run java/tomcat under nsjail
I've tried several options but JVM can't reserve mem 
`Could not reserve enough space for 262144KB object heap`
I've tried 
`/usr/sbin/nsjail --user tomcat:tomcat --group tomcat:tomcat -R /etc/alternatives -R /etc/tomcat -R /etc/sysconfig/tomcat -R /etc/java -R /bin/ -R /lib -R /lib64/ -R /usr/ -T /dev -R /dev/urandom -T /tmp -B /usr/share/tomcat -B /var/log/tomcat/ -e -- /usr/libexec/tomcat/server start`

and 
`/usr/sbin/nsjail --user tomcat:tomcat --group tomcat:tomcat -R /etc/alternatives -R /etc/tomcat -R /etc/sysconfig/tomcat -R /etc/java -R /bin/ -R /lib -R /lib64/ -R /usr/ -T /dev -R /dev/urandom -T /tmp -B /usr/share/tomcat -B /var/log/tomcat/ -e -- /bin/java`

and 
`/usr/sbin/nsjail --user tomcat:tomcat --group tomcat:tomcat -R /etc/alternatives -R /etc/tomcat -R /etc/sysconfig/tomcat -R /etc/java -R /bin/ -R /lib -R /lib64/ -R /usr/ -T /dev -R /dev/urandom -T /tmp -B /usr/share/tomcat -B /var/log/tomcat/ -e -- /bin/strace /bin/java`

![captura de pantalla 2017-05-20 a las 16 12 31](https://cloud.githubusercontent.com/assets/469221/26276418/abda9b5e-3d77-11e7-8126-89a30b03a56b.png)

![captura de pantalla 2017-05-20 a las 16 15 25](https://cloud.githubusercontent.com/assets/469221/26276419/b6a06fdc-3d77-11e7-9c34-d187ed8cfca7.png)

**Comment by robertswiecki** [comment]
I think you need to play with --rlimit_as, also other --rlimit's will be useful, e.g. --rlimit_fsize will probably need to be increased as well

**Comment by robertswiecki** [comment]
If you get to some stable config, feel free to put it in https://github.com/google/nsjail/tree/master/configs

**Comment by ultmaster** [comment]
I've encountered the same problem. I think set rlimit_as to inf works. Use cgroup to restrict memory instead of rlimit. JVM is not happy with rlimit.

**Comment by robertswiecki** [comment]
Hm... I think we should set RLIMIT_AS to RLIM64_INFINITY by default. This rlimit is a very imperfect approximation of RAM used (since RLIMIT_RSS doesn't work in Linux), and many tools use small amounts of RAM bug big amounts of VM, e.g. ASAN sanitizers of Scudo Memory Allocator. I'll think about it.

**Comment by robertswiecki** [comment]
I've increased the limit to 4GiB for now, but the overall goal is to set it to RLIM64_INFINITY
