### ISSUE TITLE
clone_newcgroup = true; 

### ISSUE THREAD

**Issue by eli-zr** [google/nsjail#175]

**Comment by eli-zr** [comment]
When time namespace support was added, it seems that the clone_newcgroup flag was overridden (set to false).
I guess the intention was to set clone_newtime to false?

**Comment by eli-zr** [comment]
see line 438 in cmdline.cc

**Comment by robertswiecki** [comment]
Ah.. my mistake, fixed with 62879de5de61c1e1152c975ced29e3c9af7318e6
