### ISSUE TITLE
Using cgroup

### ISSUE THREAD

**Issue by eli-zr** [google/nsjail#178]
It seems like I'm missing something regarding the usage of cgroups, as I'm not able to use it. nsjail gets the parent name (defaulted to NSJAIL) and builds a path under the relevant controller. For example: "/sys/fs/cgroup/pids/NSJAIL/NSJAIL.26876"
To build this path, mkdir API is used, however it seems like a full path is given where both NSJAIL and NSJAIL.26876 folders do not exist, and I wonder how it is supposed to work. The mkdir util has a -p option to build a full path, but not the API.

When I try it I usually get something like mkdir('/sys/fs/cgroup/pids/NSJAIL/NSJAIL.26958', 0700) failed: No such file or directory, and it is not related permissions.
I'll add that if I create the parent externally it does work.

I'd appreciate a clarification on what is missing.

**Comment by happyCoder92** [comment]
nsjail assumes the parent cgroup is pre-existing.
As an example documentation for pids cgroup:
```
--cgroup_pids_parent VALUE
	Which pre-existing pids cgroup to use as a parent (default: 'NSJAIL')
```
So creating the parent externally is how it's supposed to work :)
