### ISSUE TITLE
build on CentOS 7 with ProtoBuf support

### ISSUE THREAD

**Issue by farconada** [google/nsjail#18]
Opened this issue just for doc purpose:

If you try to compile under CentOS with ProtoBuf support you will have this error
``
cc -o nsjail nsjail.o cmdline.o config.o contain.o log.o cgroup.o mount.o net.o pid.o sandbox.o subproc.o user.o util.o uts.o config.pb-c.o kafel/libkafel.a protobuf-c-text/protobuf-c-text/.libs/libprotobuf-c-text.a -Wl,-z,now -Wl,-z,relro -pie -Wl,-z,noexecstack -lprotobuf-c
/bin/ld: protobuf-c-text/protobuf-c-text/.libs/libprotobuf-c-text.a(protobuf_c_text_libprotobuf_c_text_la-generate.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
protobuf-c-text/protobuf-c-text/.libs/libprotobuf-c-text.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [nsjail] Error 1
``

to solve this issue you have to 
` cd protobuf-c-text/ ; export CFLAGS=-fPIC; ./autogen.sh; make `
then you can go back to nsjail dir and build as usual

**Comment by robertswiecki** [comment]
Thanks.. should be fixed in HEAD. I've also changed incorrect protobuf-c pkg-config check (it was for C++).
