### ISSUE TITLE
libprotobuf error when running Docker

### ISSUE THREAD

**Issue by phoebetse** [google/nsjail#195]
I get the following error when running nsjail in the provided `Dockerfile`:

```bash
$ docker build -t nsjailcontainer
Successfully built ...
Successfully tagged nsjailcontainer:latest

$ docker run -it nsjailcontainer nsjail
nsjail: error while loading shared libraries: libprotobuf.so.23: cannot open shared object file: No such file or directory
```

Is this a bug in the dockerfile? Or is there something I'm missing?

**Comment by happyCoder92** [comment]
Hi! I cannot reproduce the issue.
```
$ git clone https://github.com/google/nsjail.git
$ cd nsjail
$ docker build -t nsjailcontainer .
[...]
Successfully built 9000351bf6ab
Successfully tagged nsjailcontainer:latest
$ docker run -it nsjailcontainer nsjail
 Usage: nsjail [options] -- path_to_command [args]
[...]
```

**Comment by phoebetse** [comment]
weird, i'm no longer seeing the issue anymore. maybe something intermittent? thanks for looking into this!

**Comment by rorynugent** [comment]
Usually this means you are missing the shared library on your system. You can install it like so if `apt` is your package manager:

`sudo apt install libprotobuf23`
