### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by 12D687** [google/nsjail#217]
I can't compile nsjail:
 net.cc:54:10:` fatal error: netlink/route/link.h: No such file or directory
   54 | #include <netlink/route/link.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by robertswiecki** [comment]
You need to install libnetlink-route. Under debian it'd be

```apt install libnl-route-3-200:amd64```
