### ISSUE TITLE
nsjail after fork() on existing process 

### ISSUE THREAD

**Issue by jeroen** [google/nsjail#23]
Is it possible to apply nsjail to an existing process via the C api? Similar to how e.g. `chroot(2)` or `setrlimit(2)` in Linux apply restriction on the current process?

My use case is that I have a faily complicated application, in which I want to run a piece of untrusted code in a temporary fork with some restrictions (without `execv()`) , and when it's done have the parent process kill of the entire child's process tree.

**Comment by robertswiecki** [comment]
nsjail doesn't have C API. You might want to try minijail, which, if I'm not mistaken, offers some API.
