### ISSUE TITLE
Why changing the theme so often?

### ISSUE THREAD

**Issue by andy0130tw** [google/nsjail#27]
Hi, I am not to be joking, but the theme changes over these months are a little annoying. I am a developer try to build things with nsjail. Checking things on the official site is often while I am getting used to this tool, but every time I open the site I am stunned because the site is keep changing theme with content almost unchanged.

Are you not sure about what theme fits? Personally, among those you tried, I recommend `jekyll-theme-slate` the most. I am sorry for this non-productive issue, but changing theme is unproductive, also.

**Comment by robertswiecki** [comment]
I was looking for a one which offers ability to show good command-line things (help etc..).

But, slate it is :)
