### ISSUE TITLE
Creating symbolic link within jail?

### ISSUE THREAD

**Issue by wsxiaoys** [google/nsjail#29]
Hi
I'm trying to create symbolic link for /proc/self/fd to /dev/fd inside the jail. So the process substitute could work in bash. /proc itself is mounted through procfs.

one solution is to create /dev tmpfs with rw, and create symbolic link before bash started. 
Is this something can be configured with mount, any suggestions?

**Comment by robertswiecki** [comment]
No such functionality now, but I'm open to suggestions, esp. if you'd like something like that added in configuration files. Possibly is_link = true, and some code in mount.c could work.

**Comment by robertswiecki** [comment]
Added it in https://github.com/google/nsjail/commit/e4aba733857a8b9bf8a93d8e09a1909fbd744ff4

**Comment by wsxiaoys** [comment]
wow, thanks for the ⚡ fast update!
