### ISSUE TITLE
Can't run as different user when --disable_clone_newuser is passed in

### ISSUE THREAD

**Issue by nathancrandall** [google/nsjail#35]
When running this utility with user namespaces enabled, generally you'll have the outside UID/GID be an unprivileged user, and the inside UID/GID be root.  This is needed for nsjail, since the namespace user needs the capability to mount the root tmpfs for the chroot'd environment (in `/dev/shm/nsjail.root`).

However, if we don't want to run with `clone_newuser` (maybe because we don't want to expose that attack surface, or our kernel doesn't support it), the `mount()` operation will fail.  This is because the `containUserNs()` helper is called first, and simply sets our uid/gid if user namespaces are disabled.  We are dropping our privileges too early for anything else important to take place (like the `mount()` operations in `containInitMountNs`).

```
bool containContain(struct nsjconf_t * nsjconf)
{
    if (containUserNs(nsjconf) == false) { <-- uid/gid dropped here.
        return false;
    }
    if (containInitPidNs(nsjconf) == false) {
        return false;
    }
    if (containInitMountNs(nsjconf) == false) {
        return false;
    }
    if (containInitNetNs(nsjconf) == false) {
        return false;
    }
    if (containInitUtsNs(nsjconf) == false) {
        return false;
    }
    if (containInitCgroupNs() == false) {
        return false;
    }
    if (containDropPrivs(nsjconf) == false) {
        return false;
    }
    -----> containUserNs() should be moved here. <------
/* */
    /* As non-root */
    if (containCPU(nsjconf) == false) {
        return false;
    }
    if (containSetLimits(nsjconf) == false) {
        return false;
    }
    if (containPrepareEnv(nsjconf) == false) {
        return false;
    }
    if (containMakeFdsCOE(nsjconf) == false) {
        return false;
    }
    return true;
}
```

Let's try running `nsjail -u <non_root> -g <non_root> -R /bin -R /sbin -R /lib -R /lib64 -R /usr -c /tmp/user --disable_clone_newuser -- /bin/bash`

Sure enough, running this without the patch we get:

```
....
[2017-07-24T19:04:01-0700] [D][1] mountMkdirAndTest():255 Created accessible directory in '/dev/shm/nsjail.root'
[2017-07-24T19:04:01-0700] [E][1] mountInitNsInternal():312 mount('/dev/shm/nsjail.root', 'tmpfs'): Operation not permitted
....
```

Running with the patch, we get:

```
....
[2017-07-24T19:04:56-0700] [D][1] mountMkdirAndTest():255 Created accessible directory in '/dev/shm/nsjail.root'
[2017-07-24T19:04:56-0700] [D][1] mountMkdirAndTest():255 Created accessible directory in '/dev/shm/nsjail.tmp'
[2017-07-24T19:04:56-0700] [D][1] mountMount():125 mounting 'src:'/tmp/user' dst:'/' type:'' flags:MS_RDONLY|MS_BIND|MS_REC|0 options:'' isDir:true'
....
```

Let me know if you have any questions or if the proposed patch introduces other issues.

-Nathan

**Comment by robertswiecki** [comment]
The solution is probably a bit more convoluted than what you described, but please try your command at HEAD. It should work now.
