### ISSUE TITLE
Cleanup mounts if initialization fails

### ISSUE THREAD

**Issue by nathancrandall** [google/nsjail#36]
Currently, nsjail mounts by default into `/dev/shm/nsjail.root` and `/dev/shm/nsjail.root/proc`.  If you specify other mounts with `-R` e.g. `-R /lib` or other similar options, we mount even more.  If any of the other initialization routines fail after these have been mounted, we end up with a bunch of stale mount points.  If you keep re-running nsjail (and it fails somewhere in initialization post-mount), you'll soon end up with hundreds of identical mount entries!  Of course if it fails too late, we won't have the privileges to unmount, but there should at least be some attempt at cleanup.

**Comment by robertswiecki** [comment]
I think it's fixed now with making the whole / private before mounting. Please feel free to try it it HEAD
