### ISSUE TITLE
Manual page for nsjail

### ISSUE THREAD

**Issue by jvvv** [google/nsjail#38]
I'm preparing a package of nsjail for [CRUX](https://crux.nu) linux and wish to include at least a basic manual page for usage.

I have worked up a manual page by starting with the output of help2man and then have done a good deal of cleanup from that point. I think that it's at a useable stage.

If including it here is of interest, I can do a PR.
Content can be previewed at https://github.com/jvvv/nsjail/blob/master/nsjail.1.

**Comment by robertswiecki** [comment]
Absolutely, feel free to create some docs for man/docs.

Thanks!
