### ISSUE TITLE
Download links on website download `gh-pages` branch, not `master`

### ISSUE THREAD

**Issue by jadengeller-asana** [google/nsjail#40]
Both the `.tar.gz` and the `.zip` download links on http://nsjail.com/ download the actual GitHub Pages website instead of the program. I assume this is a mistake.

**Comment by jvvv** [comment]
Looks to me like the _config.yml in the gh-pages branch needs to include the 'tar_url' and 'zip_url', which are mentioned on this [page](https://help.github.com/articles/repository-metadata-on-github-pages/). I'm not certain, but I think it's a safe guess that the example values are not to much different from the defaults if unset.

**Comment by robertswiecki** [comment]
Thanks for the report - I re-created the gh-pages branch, and it seems that it removed the links. Maybe it's not the best option here, but it solved the problem :) (links at the github page instead)
