### ISSUE TITLE
Missing dependency rule for config.pb.h

### ISSUE THREAD

**Issue by jvvv** [google/nsjail#41]
Commit https://github.com/google/nsjail/commit/5c2d98562c64870c038aeccc1e11771138cb4c8a leaves config.pb.h no rule to get generated. Even though the $(SRCS_PB) rule will do the work necessary, the last depend line:
`config.pb.o: config.pb.h`
will not be satisfied.

Adding the header to the SRCS_PB definition:
`SRCS_PB = $(SRCS_PROTO:.proto=.pb.cc) $(SRCS_PROTO:.proto=.pb.h)`
allows for successful compilation.

A different fix could be to add a separate variable for the header:
`HDRS_PB = $(SRCS_PROTO:.proto=.pb.h)`
then, later, an empty rule for dependency resolution:
`$(HDRS_PB): $(SRCS_PROTO)`

As a side note, I think 'clear' is a typo of 'clean' on the .PHONY target line in the Makefile

**Comment by robertswiecki** [comment]
Yup, thanks for the report. I think I've fixed it in some recent changes to the Makefile. Please re-open if any problems still persist.
