### ISSUE TITLE
Ability to use additional File Descriptors on spawn

### ISSUE THREAD

**Issue by Marak** [google/nsjail#47]
We've got a situation where additional custom data is being passed from the child process on FD 3.

It seems when we try to spawn the same application using `nsjail`, there is no way to open up the additional File Descriptor we need.

Is there any easy way we can fix this? I found some references in the code, but it seems mostly hard-coded to only work with FD 0,1,2

Thank you.

**Comment by robertswiecki** [comment]
Hi, maybe

--pass_fd 

?

**Comment by Marak** [comment]
@robertswiecki -

That worked! Thank you!

I didn't see the `--pass_fd` option in the documentation.

`nsjail` is really quite nice piece of software. Thank you for making this.

**Comment by robertswiecki** [comment]
Thanks!
