### ISSUE TITLE
Feature request: rlimit max setting in config

### ISSUE THREAD

**Issue by jvvv** [google/nsjail#48]
One of my primary usages of nsjail is for isolated build containers. These require quite a lot of resources, so I often set some or most of the rlimit values to 'max' from the command line. It would be handy to be able to do this via the config file.

**Comment by robertswiecki** [comment]
Please try with https://github.com/google/nsjail/commit/dbc6fab582b7466e20b47f41eb62d1baf949d9cb

**Comment by jvvv** [comment]
Thank you very much for your quick attention to this! It works like a charm, with the exception of this (typo, I think): https://github.com/google/nsjail/commit/dbc6fab582b7466e20b47f41eb62d1baf949d9cb#commitcomment-24835260

**Comment by jvvv** [comment]
Also, perhaps this should also be adjusted: https://github.com/google/nsjail/commit/e89a6f0c2465609b9fd01bf2c8cf66da1421ae4c#commitcomment-24836455

**Comment by robertswiecki** [comment]
Ah, yes. Nice catch!
