### ISSUE TITLE
The limit max_conns_per_ip is broken

### ISSUE THREAD

**Issue by ShikChen** [google/nsjail#62]
https://github.com/google/nsjail/blob/e2529ce04f0d5a278aa5d8e19ccb2f6eb0bc760f/net.c#L165-L178

There is a redundant dereference operator in the `sizeof(...)` of `memcmp`, so it would only compare the first byte of address and reject new connections too aggressively.

The relevant structures:

``` c
struct sockaddr_in6 {
    sa_family_t     sin6_family;   /* AF_INET6 */
    in_port_t       sin6_port;     /* port number */
    uint32_t        sin6_flowinfo; /* IPv6 flow information */
    struct in6_addr sin6_addr;     /* IPv6 address */
    uint32_t        sin6_scope_id; /* Scope ID (new in 2.4) */
};

struct in6_addr {
    unsigned char   s6_addr[16];   /* IPv6 address */
};
```

**Comment by robertswiecki** [comment]
Thanks for the report - fixed with https://github.com/google/nsjail/commit/9e355cbcfc1c67cfc1ee4f408ed842b9cc69d6d9
