### ISSUE TITLE
Does nsjail support cgroup v2?

### ISSUE THREAD

**Issue by sebest** [google/nsjail#65]

**Comment by robertswiecki** [comment]
Hi, no. though it should be easy-ish to add, look at the https://github.com/google/nsjail/blob/master/cgroup.c

Also, with newer kernels it seems it's possible to mount cgroup2 fs inside the jail, given that CLONE_NEWCGROUP is enabled. This works, though I haven't figured it out yet how to use it to make it work from within jail.

If you'd like to play with it:

```
$ ./nsjail --chroot /chroot/ --keep_caps -u 0 -g 0 -- /bin/sh -i
# mkdir /tmp/cgroup2
# mount -t cgroup2 none /tmp/cgroup2
# cd /tmp/cgroup2
# find
.
./cgroup.subtree_control
./cgroup.events
./cgroup.controllers
./cgroup.procs
```
