### ISSUE TITLE
Unable to set nosuid or nodev options on tmpfs mount using config file

### ISSUE THREAD

**Issue by rutsky** [google/nsjail#70]
When I try to mount `/tmp` in a container like this:

```
mount {
  dst: "/tmp"
  fstype: "tmpfs"
  rw: true
  options: "nosuid,nodev"
}
```

I get `Invalid argument` error:

```
[2018-01-08T00:40:27.513440+0100] [D][1] mountMount():124 Mounting 'src:'[NULL]' dst:'/tmp' type:'tmpfs' flags:0 options:'nosuid' isDir:true'
[2018-01-08T00:40:27.513516+0100] [W][1] mountMount():205 mount('src:'[NULL]' dst:'/tmp' type:'tmpfs' flags:0 options:'nosuid' isDir:true') src:'none' dst:'/tmp/nsjail.root//tmp' failed: Invalid argument
```

My guess is that in order to enable `nosuid`, `nodev`, `noexec` in mount syscall it's also required to specify them in `mountflags` argument as `MS_NOSUID`, `MS_NODEV`, `MS_NOEXEC`.

Harder and less straightforward, but more user friendly solution would be to parse options and set appropriate flags, as `mount` command line utility does.
Easier solution is to add `mountflags` field to `MountPt` config proto message and require setting those flags (`MS_NOSUID` and others) there.

**Comment by robertswiecki** [comment]
These are not options (option arg for mount()) but a flag, we don't currently have config val for setting MS_NOSUID,MS_NOV etc, onlt MS_RDONLY, though we could add it I guess

**Comment by mtis88** [comment]
👍 
I'd like the ability to create a tmpfs with noexec.

**Comment by happyCoder92** [comment]
Hi,

I just added relevant fields to config proto.

```
mount {
  dst: "/tmp"
  fstype: "tmpfs"
  rw: true
  nosuid: true
  nodev: true
}
```

Should work now.
Also `noexec` is available in the same fashion.

**Comment by mtis88** [comment]
Thanks!
