### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by goome** [google/nsjail#73]
Linux ubuntu 4.10.0-28-generic x86_64
 g++  5.4.0 20160609

In file included from config.cc:41:0:
log.h:46:15: error: ‘namespace log { }’ redeclared as different kind of symbol
 namespace log {
               ^
In file included from /usr/include/features.h:367:0,
                 from /usr/include/fcntl.h:25,
                 from config.cc:22:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:109:1: note: previous declaration ‘double log(double)’
 __MATHCALL_VEC (log,, (_Mdouble_ __x));

**Comment by robertswiecki** [comment]
Thanks for the report, hopefully fixed with https://github.com/google/nsjail/commit/97278f191b48daecae3483ca6e9194b4e715478f
