### ISSUE TITLE
--disable_clone_newuser ignored

### ISSUE THREAD

**Issue by Inveracity** [google/nsjail#78]
Heya I'm trying to run this command
```
root@42c59e018224:/# nsjail -Mo --chroot /chroot/ --disable_clone_newcgroup --disable_clone_newuser -E LANG=en_US.UTF-8 -R/usr -R/lib -R/lib64 --user nobody --group nogroup --time_limit 2 --disable_proc --iface_no_lo --cgroup_mem_max 50000 --cgroup_pids_max 1 --quiet -- /usr/bin/python3.6 -ISq -c "print('test')" 
```
but I run into the following error message:
```
[2018-05-30T12:33:13+0000] [E][16] void subproc::runChild(nsjconf_t*, int, int, int)():441 clone(flags=CLONE_NEWNS|CLONE_NEWUTS|CLONE_NEWIPC|CLONE_NEWPID|CLONE_NEWNET|SIGCHLD) failed. You probably need root privileges if your system doesn't support CLONE_NEWUSER. Alternatively, you might want to recompile your kernel with support for namespaces or check the setting of the kernel.unprivileged_userns_clone sysctl: Operation not permitted
```

It appears the `--disable_clone_newuser` is being ignored?

**Comment by Inveracity** [comment]
I ended up doing this
```
nsjail -Mo \
--rlimit_as 700 \
--chroot / \
-E LANG=en_US.UTF-8 \
-R/usr -R/lib -R/lib64 \
--user nobody \
--group nogroup \
--time_limit 2 \
--disable_proc \
--iface_no_lo \
--quiet -- /usr/local/bin/python3.6 -ISq -c "print('test')"
```
and run the docker container in privileged mode

**Comment by robertswiecki** [comment]
Using ```--chroot /``` and ```-R /usr``` duplicates itself, as-in, both ```/``` will be mounted RO, and ```/usr``` will be mounted RO. But ```/usr``` would be there anyway as it's part of ```/```. Try without ```--chroot /```. Like this

```nsjail -Mo --rlimit_as 700 -E LANG=en_US.UTF-8 -R/usr -R/lib -R/lib64 --user nobody --group nogroup --time_limit 2 --disable_proc --iface_no_lo --quiet -- /usr/bin/python3.6 -ISq -c "print('test')"```

As for ```--disable_clone_newuser```, it requires running nsjail from root (```man user_namespaces``` for ```CLONE_NEWUSER```)

**Comment by Inveracity** [comment]
Aha! Thank you 👍
