### ISSUE TITLE
log 'Parsing configuration from file'is always sent to stderr

### ISSUE THREAD

**Issue by ukai** [google/nsjail#81]
Even if I specify -l (--log), 'Parsing configuration from <file>' log message is always sent to stderr.

**Comment by ukai** [comment]
https://github.com/google/nsjail/commit/97278f191b48daecae3483ca6e9194b4e715478f ?

**Comment by robertswiecki** [comment]
Hi,

I reworked logging slightly in https://github.com/google/nsjail/commit/04627982d0881a2bfab0e1668ab350544fd79ae5 - hope this helps

**Comment by ukai** [comment]
thanks!
