### ISSUE TITLE
Mapping files or folders with annoying names

### ISSUE THREAD

**Issue by tylerni7** [google/nsjail#92]
If one wants to map a file or folder from the command line, the path cannot contain a colon character anywhere, or it is assumed that this is the delimited separating the source and destination.

For example, `-R /tmp/foo:bar:/foobar` will understandably not work.

While one workaround would be to use a configuration file, it would be great if it were still possible to handle these cases on the command line. For example, maybe there could be a set of two-argument options which take in a source and dest separately, so the syntax would look like `--bindmount_ro2 /tmp/foo:bar /foobar`

**Comment by happyCoder92** [comment]
The two-argument option does not follow [Utility Argument Syntax](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html) and is not straightforward to implement.

A colon isn't very common in pathnames and, as you already mentioned, there are workarounds.
Another one is to first bind-mount `/tmp/foo:bar` to e.g. `/tmp/foo_bar` and then use the latter with nsjail's command line.

**Comment by robertswiecki** [comment]
Hi @tylerni7, please re-open if you feel strongly about it.
